# fly.toml app configuration file generated for docwood on 2024-04-22T23:54:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docwood'
primary_region = 'lax'

[deploy]
  release_command = '.fly/release.sh'

[env]
  PORT = '8910'
  REDWOOD_DISABLE_TELEMETRY = '1'

[http_service]
  internal_port = 8910
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
